- package.json
ref: https://github.com/oneteam-dev/draft-js-export-html/commit/a5c2b0010fde1e447956f9920684af176a1dcff5
> Update `draft-js-export-html` to v0.0.8-oneteam

- src/Body.js
@ngs Please review 🙇 
Tab character can not be displayed in html. has changed in 4spaces.
> Press tab key insert 4 spaces

- package.json
- src/Body.js
- src/functions/index.js
- src/functions/splitBlockInContentStateIfCursorAtStart.js
Handle paste text to render webcard
> Tweak new line handler, and

- package.json
> Update react-oneteam version

- yarn.lock
Bump [draft-js-oneteam-rte-plugin](https://github.com/oneteam-dev/draft-js-oneteam-rte-plugin) from 0.4.4 to 0.4.5
> Bump draft-js-oneteam-rte-plugin from 0.4.4 to 0.4.5

- examples/App.js
- package.json
- src/encoding/index.js
- yarn.lock
plugins に導入した `editExceptOuterLink` により url 内の意図しない emoji 化を避ける
> Fix emoji encoding

- src/RichTextEditor.js
Add handlers
====
- handlePastedText: https://draftjs.org/docs/api-reference-editor.html#handlepastedtext
- handleBeforeInput: https://draftjs.org/docs/api-reference-editor.html#handlebeforeinput
> Add handlePastedText/handleBeforeInput

- package.json
- yarn.lock
see: https://github.com/oneteam-dev/react-oneteam/pull/20
> Upgrade react-oneteam

- package.json
- yarn.lock
see: https://github.com/oneteam-dev/react-oneteam/pull/21
> Upgrade react-oneteam v0.4.5

- yarn.lock
1 macaddress vulnerabilities found in yarn.lock
> Upgrade macaddress

- examples/Editor.js
- src/RichTextEditor.js
- src/plugins/hashtagList/index.js
- src/plugins/hashtagList/style.css
- src/plugins/index.js
> Add hashtags suggest 

- src/RichTextEditor.js
|**before**|**after**|
|---|---|
|![before](https://user-images.githubusercontent.com/12182520/65173093-1ccbbe00-da89-11e9-988e-c527b7d63140.gif)|![after](https://user-images.githubusercontent.com/12182520/65173107-235a3580-da89-11e9-9e95-5b7f757f54e2.gif)|
> Fix hashtag suggest search filter bug

- src/RichTextEditor.js
|**before**|**after**|
|--|--|
|![before](https://user-images.githubusercontent.com/12182520/65487285-8876b680-dee1-11e9-96d6-6f2e4884f406.gif)|![after](https://user-images.githubusercontent.com/12182520/65487316-96c4d280-dee1-11e9-8be7-a88f0022d7cf.gif)|
> Disable hashtag suggest in code block

- src/RichTextEditor.js
Jira: https://oneteam-dev.atlassian.net/browse/TC-555
Issue: https://github.com/oneteam-dev/comuque-frontend/issues/4026
フォーカス時に背景色を変更するためにイベントを取得可能にする
`examples/Editor.js` に `console.log` を記述して確認しました。
> Focus / Blur イベントを取得する

- package.json
- yarn.lock
Reverts oneteam-dev/oneteam-rte#147
> Revert "Bump webpack-dev-server from 2.11.1 to 3.1.11"

- yarn.lock
> Bump eslint from 4.18.1 to 4.18.2

- .circleci/config.yml
@joraku 
Issue: #158 [TC-162] js-yaml のアップデート 
エラーについて
https://github.com/oneteam-dev/oneteam-rte/issues/158#issuecomment-599931257
目的
====
> デプロイ時のエラーを解消する

- .circleci/config.yml
Reverts oneteam-dev/oneteam-rte#161
> Revert "デプロイ時のエラーを解消する"

- .circleci/setup-npm.sh
- package.json
> update npm user

- .circleci/setup-npm.sh
> Revert "update npm user"

- src/utils/mentionSuggestionsFilter.js
https://oneteam-dev.atlassian.net/browse/TC-417
上記の対応の一部です。
後ほど comuque-frontend に取り込んで TC-417 の本対応 PR を出します。
> [TC-417] Don't limit the number of mentions to 8

- src/utils/mentionSuggestionsFilter.js
https://github.com/oneteam-dev/comuque-frontend/pull/4224#issuecomment-653435639
の警告に対する修正です。
> Fix duplicate key warning
